default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sloppy_hour_development

test:
  <<: *default
  database: sloppy_hour_test

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
