class DealOccurrence < ActiveRecord::Base
  belongs_to :schedulable, polymorphic: true

  default_scope { order('date ASC') }

  scope :remaining, lambda{where(["date >= ?",Time.now])} #generated by schedulable gem
  scope :previous, lambda{where(["date < ?",Time.now])} #generated by schedulable gem
  scope :today, -> { includes(:schedulable).where(:date => Date.today.midnight..Date.today.end_of_day) }
  
end
